### ISSUE TITLE
Func with string params, IndeterminateDatatypeError

### ISSUE THREAD

**Issue by dyens** [CanopyTax/asyncpgsa#109]
Hi!
Thank you for asyncpgsa.

I have some problems when  use `sql.func` with sting arguments. 
I try to use `func.jsonb_build_object('key_name', field.key)` construction.

Actually, the simple example to reproduce this error is :

```python
query = select([func.count('*')]).select_from(table)
records = await conn.fetch(query)

  File "asyncpg/protocol/protocol.pyx", line 163, in prepare
asyncpg.exceptions.IndeterminateDatatypeError: could not determine data type of parameter $1
```

**Comment by alairock** [comment]
Instead of `'*'` use the sqlalchemy model reference to the field. 

```python
select([func.count(table.c.id)]).select_from(table)
```

But to specifically solve your problem, you could use `literal_columns`.

```python
query = select([literal_column("json_build_object('foo',1,'bar',2) as bob")]).select_from(db.process_nodes)
```

and if the field `field.key` happens to come from user input, you can bind the params using `bindparam()`
https://docs.sqlalchemy.org/en/13/core/sqlelement.html?highlight=bindparam#sqlalchemy.sql.expression.bindparam

**Comment by dyens** [comment]
Thank you for you answer!
